### PR TITLE
Homepage updates

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- ~Bumps Largo to 0.6.4~ removed, see https://github.com/INN/umbrella-mwcir/issues/32#issuecomment-587596894
- Copies largo's `partials/sticky-posts.php` to this repo, removes the related posts section, adds a top term, and embiggens the image
- Makes the Homepage Bottom widget area encompass one single column, rather than alternating left/right columns.
- Adds homepage-specific styles to space out the widgets in the homepage bottom area and add borders between them.

Screenshot_2020-02-17 Investigate Midwest - The Midwest Center for Investigative Reporting 2
Screenshot_2020-02-17 Investigate Midwest - The Midwest Center for Investigative Reporting

## Why

Homepage changes for #27
Largo update for #32

## Testing/Questions

Features that this PR affects:

- Homepage

Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [x] Should the text in these widgets not wrap around the images?
- [x] Should this PR also implement the before-footer section from the wireframe?

Screen Shot 2020-02-17 at 17 08 22

Steps to test this PR:

1. Check out this update
2. From the root of the repo, `git submodule update --init --recursive` to update Largo
3. In Appearance > Theme Options > Layout, (`/wp-admin/themes.php?page=options-framework` if you're affected by https://github.com/INN/largo/issues/1573), set:
    - Home Template to "Blog"
    - Sticky Posts to show
    - Homepage Bottom to widgets
4. In Appearance > Widgets, put a number of Recent Posts widgets there.
    - titles set to category names
    - draw from various categories
    - 3 posts
    - 140px thumbnails, left
    - yes byline
    - hide date
5. View the homepage at various screen sizes.

### CODE REVIEW

**Comment by joshdarby** [comment]
Should we remove the
```
padding-left: 2.5%;
padding-right: 2.5%;
``` 
https://github.com/INN/largo/blob/512da701664b329f2f92244bbe54880a6e146431/less/inc/responsive-768px-979px.less#L28-L36
from the widgets?

With that padding, they're out of line with the top post

With padding:
Screen Shot 2020-02-18 at 9 28 45 AM

Without padding:
Screen Shot 2020-02-18 at 9 28 39 AM

**Comment by joshdarby** [comment]
> Should the text in these widgets not wrap around the images?
> Should this PR also implement the before-footer section from the wireframe?

@MirandaEcho ?

**Comment by benlk** [comment]
Fixed the padding issue that Josh noted in https://github.com/INN/umbrella-mwcir/pull/35#issuecomment-587488169 with d0a9164

Screen Shot 2020-02-18 at 13 19 04


Also removed the Largo 0.6.4 bump from this PR for the reasons noted in https://github.com/INN/umbrella-mwcir/issues/32#issuecomment-587596894

**Comment by MirandaEcho** [comment]
> > Should the text in these widgets not wrap around the images?
> > Should this PR also implement the before-footer section from the wireframe?
> 
> @MirandaEcho ?

No to the first, yes to the second, but we're at time, so we'll need to discuss. Estimate for the before footer section?

**Comment by benlk** [comment]
The present state of things is that if we put two widgets in the Before Footer widget area, they stack vertically:

Screen Shot 2020-02-19 at 12 10 24


We'd want to do something like this pseudocss:

```
widget-area {
   flexy: yep
   flex-wrap: yep
}
widget-area widget {
   flex-shrink: no
   flex-grow: yep
   flex-basis: whatever the standard sidebar width is, call it 320px
}
```

so that widgets can grow as necessary, but don't get too squished. Maybe some per-widget styles so that the "Member of" widget has a max width and we get that asymmetrical layout from the mockup, but first we'd need to know what the widgets that will be there are.

**Estimate: 30m,** but first we need to know the widgets that will be there. In the above screenshot, I've used a text widget with sponsor markup that happened to be laying around in the admin.

```html
<a href="http://www.journalismfoundation.org/"><img src="https://investigatemidwest.org/wp-content/uploads/2012/11/ene.png" alt="ethics and excellence journalism foundation"></a>

<a href="http://www.mccormickfoundation.org/"><img src="https://investigatemidwest.org/wp-content/uploads/2012/11/mccormick.png" alt="mccormick foundation"></a>
```

**Comment by MirandaEcho** [comment]
Widgets for the footer are these ones: 
Screen Shot 2020-02-19 at 2 18 20 PM

**Comment by benlk** [comment]
Those appear to be images in textwidgets. We can accommodate that. Shall we proceed with the ~30m of work?

**Comment by MirandaEcho** [comment]
@benlk proceed, thanks!

**Comment by benlk** [comment]
On narrower screens, they wrap:

Screen Shot 2020-02-21 at 18 55 44

On wider screens, they sit side-by-side:

Screen Shot 2020-02-21 at 18 55 50

Widget content to test:

Sponsors:
```html
<a href="http://www.journalismfoundation.org/"><img src="https://investigatemidwest.org/wp-content/uploads/2012/11/ene.png" alt="ethics and excellence journalism foundation" width="200px"></a>

<a href="http://www.mccormickfoundation.org/"><img src="https://investigatemidwest.org/wp-content/uploads/2012/11/mccormick.png" alt="mccormick foundation" width="200px"></a>

<a href="http://www.mccormickfoundation.org/"><img src="https://investigatemidwest.org/wp-content/uploads/2012/11/mccormick.png" alt="mccormick foundation" width="200px"></a>
```

Member of:
```
<img alt="Member" class="attachment-full" src="https://investigatemidwest.org/wp-content/uploads/2016/06/GIJN-logo-sm.png" width="422" height="57">
```


----

This is mergeable and deployable in its present state; config items are as noted in the "Testing" section at the top of this PR.

**Pull request merged**
